version: "3.8"

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - django
      - daphne

  django:
    build: .
    image: swanycastle/django:latest
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: >
      sh -c "echo 'Starting Gunicorn' &&
             gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 4"

  daphne:
    build: .
    image: swanycastle/daphne:latest
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "9000:9000"
    command: >
      sh -c "echo 'Starting Daphne' &&
             daphne -b 0.0.0.0 -p 9000 config.asgi:application"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
