# Generated by Django 5.0.2 on 2024-03-13 09:47

import django.db.models.deletion
import feeds.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_remove_feed_content_remove_feed_user_and_more'),
        ('reviews', '0003_review_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='reviews',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_reviews', to='reviews.review'),
        ),
        migrations.AddField(
            model_name='feed',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feed',
            name='title',
            field=models.CharField(default=feeds.models.Feed.default_title, max_length=30),
        ),
    ]
