# Generated by Django 5.0.2 on 2024-02-15 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='grade',
            field=models.CharField(default='C', max_length=10),
        ),
    ]
